### PR TITLE
Fix getPeerCertificate

### PR DESCRIPTION
**Pull request by alandotcom**
From recent Node documentation:

```
message.socket#

The net.Socket object associated with the connection.

With HTTPS support, use request.socket.getPeerCertificate() to obtain the client's authentication details.
```

https://nodejs.org/api/http.html#http_message_socket

### CODE REVIEW

**Comment by alandotcom** [comment]
Fixes #6

**Comment by joews** [comment]
This change looks good, but we can't drop support for 0.10. Can you implement this in a backwards-compatible way?

Also, can you add Node 4 to travis.yml here? I'd rather deal with this change in one PR. Thanks!

**Comment by alandotcom** [comment]
@jwhitfieldseed I think we should merge this, and release a v2 without support for v0.10. It's going to be EOL soon (along with v0.12) and there seem to be open issues with it still that affect client cert auth.

https://github.com/nodejs/node/issues/5035

**Comment by joews** [comment]
Actually it seems this is backward-compatible with 0.10 - the docs led me to assume that it wasn't. My bad!

**Comment by alandotcom** [comment]
@jwhitfieldseed updated to specify just version "4". Also, rebased against master

**Comment by joews** [comment]
:+1: thanks for the contribution. I've released it as 2.0.0.

**Pull request merged**
